name: API Health Check

on:
  workflow_dispatch: 
  schedule:
    - cron: "*/14 * * * *" # Roda a cada 14 minutos (tempo do idle)

jobs:
  alive_check:
    runs-on: ubuntu-latest
    steps:
      - name: Ping /alive endpoint
        run: |
          echo "Pingando a API..."
          curl -v --fail https://mongodb-api-purpura.onrender.com/alive
